# [job-run "mms_status simulation"]
# schedule = @every 5s
# container = mms_auto_packing
# command = python app/auto_packing_demo.py

[job-run "mms_status_mc"]
schedule = @every 1m
container = mms_status_mc
command = python app/main_status.py

[job-run "mms_status_box"]
schedule = @every 5m
container = mms_status_box
command = python app/main_status_box.py

[job-run "mms_status_device"]
schedule = @every 5m
container = mms_status_device
command = python app/main_state_device.py