
services:
  mms_app:
    image: "mic/mms_ma:1.0.0"
    environment:
      - TZ=Asia/Bangkok
    container_name: mms_app
    privileged: true
    volumes:
      - ./log:/app/log
      - ./.env:/app/.env

    command: ["python", "signal_service.py"]
    restart: always

  schedule:
    image: "mic/mms_ma:1.0.0"
    container_name: schedule
    privileged: true
    volumes:
      - ./log:/app/log
      - ./.env:/app/.env
      - ./time.json:/app/time.json

    environment:
      - TZ=Asia/Bangkok
    command: ["python", "schedule.py"]
    

  ofelia:
    image: mcuadros/ofelia:latest
    privileged: true
    container_name: ofelia
    restart: always
    volumes:
      - ./config.ini:/etc/ofelia/config.ini



